import express from "express";
import crypto from "crypto";
import PDFDocument from "pdfkit";
import axios from "axios";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import idempotencyStore from "./idempotencyStore.js";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Raw body for Razorpay signature verification ─────────────────
app.use("/webhook/razorpay", express.raw({ type: "application/json" }));
app.use(express.json());

// ── Health check ─────────────────────────────────────────────────
app.get("/", (req, res) => {
  res.json({ status: "FlowConnect Webhook Server running ✅", timestamp: new Date().toISOString() });
});

// ── Generate deterministic invoice number from payment_id ─────────
function generateDeterministicInvoiceNumber(paymentId) {
  // Hash the payment ID to get a consistent number
  const hash = crypto.createHash("sha256").update(paymentId).digest("hex");
  // Take first 8 chars of hash, convert to number
  const numericHash = parseInt(hash.substring(0, 8), 16);
  // Create invoice number with predictable format
  const invoiceNum = `INV-${String(numericHash).slice(-5).padStart(5, "0")}`;
  return invoiceNum;
}

// ── Core: Generate Invoice PDF ────────────────────────────────────
async function generateInvoice({ payment_id, amount, customer_name, customer_email, customer_phone, product_name, company_name, invoice_number_override = null }) {

  let invoice;

  // ── Try Claude AI first ───────────────────────────────────────
  try {
    const Anthropic = (await import("@anthropic-ai/sdk")).default;
    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

    const aiResp = await anthropic.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 1000,
      messages: [{
        role: "user",
        content: `Generate a professional invoice in JSON format for:
- Company: ${company_name || "FlowConnect"}
- Customer: ${customer_name}
- Email: ${customer_email}
- Payment ID: ${payment_id}
- Amount: Rs.${amount}
- Product: ${product_name || "Digital Service"}
- Date: ${new Date().toLocaleDateString("en-IN")}

Return ONLY valid JSON with these fields:
{
  "invoice_number": "INV-XXXXX",
  "company_name": "...",
  "company_tagline": "...",
  "customer_name": "...",
  "customer_email": "...",
  "invoice_date": "...",
  "due_date": "...",
  "items": [{"description": "...", "quantity": 1, "rate": 0, "amount": 0}],
  "subtotal": 0,
  "tax": 0,
  "total": 0,
  "notes": "...",
  "thank_you_message": "..."
}`
      }]
    });

    const text = aiResp.content[0].text.replace(/```json|```/g, "").trim();
    invoice = JSON.parse(text);
    // Override with deterministic invoice number for idempotency
    invoice.invoice_number = invoice_number_override || generateDeterministicInvoiceNumber(payment_id);
    console.log("🤖 Invoice generated by Claude AI");

  } catch (aiErr) {
    // ── Fallback: hardcoded invoice (used when API credits are low) ──
    console.warn(`⚠️  Claude AI unavailable (${aiErr.message}) — using fallback invoice`);

    const invoiceNum = invoice_number_override || generateDeterministicInvoiceNumber(payment_id);
    const today = new Date().toLocaleDateString("en-IN");
    const dueDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString("en-IN");
    const tax = Math.round(amount * 0.18);
    const subtotal = amount;
    const total = subtotal + tax;

    invoice = {
      invoice_number: invoiceNum,
      company_name: company_name || "FlowConnect",
      company_tagline: "India-first Automation Platform",
      customer_name,
      customer_email,
      invoice_date: today,
      due_date: dueDate,
      items: [{
        description: product_name || "Digital Service",
        quantity: 1,
        rate: amount,
        amount: amount,
      }],
      subtotal,
      tax,
      total,
      notes: `Payment ID: ${payment_id} | Thank you for choosing us!`,
      thank_you_message: "We appreciate your business. See you again! 🙏",
    };
  }

  // ── Generate PDF ──────────────────────────────────────────────
  const outputDir = path.join(__dirname, "invoices");
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);
  const filePath = path.join(outputDir, `${invoice.invoice_number}.pdf`);

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Header
    doc.fontSize(28).fillColor("#6366f1").text(invoice.company_name, 50, 50);
    doc.fontSize(10).fillColor("#6b7280").text(invoice.company_tagline, 50, 85);

    // Invoice label
    doc.fontSize(20).fillColor("#111827").text("INVOICE", 400, 50, { align: "right" });
    doc.fontSize(10).fillColor("#6b7280")
      .text(`Invoice #: ${invoice.invoice_number}`, 400, 80, { align: "right" })
      .text(`Date: ${invoice.invoice_date}`, 400, 95, { align: "right" })
      .text(`Due: ${invoice.due_date}`, 400, 110, { align: "right" });

    // Divider
    doc.moveTo(50, 130).lineTo(550, 130).strokeColor("#e5e7eb").stroke();

    // Bill To
    doc.fontSize(10).fillColor("#6b7280").text("BILL TO", 50, 145);
    doc.fontSize(12).fillColor("#111827").text(invoice.customer_name, 50, 160);
    doc.fontSize(10).fillColor("#6b7280").text(invoice.customer_email, 50, 175);

    // Table header
    doc.rect(50, 210, 500, 25).fill("#6366f1");
    doc.fontSize(10).fillColor("#ffffff")
      .text("Description", 60, 218)
      .text("Qty", 300, 218)
      .text("Rate", 370, 218)
      .text("Amount", 460, 218);

    // Table rows
    let y = 245;
    invoice.items.forEach((item, i) => {
      if (i % 2 === 0) doc.rect(50, y - 5, 500, 22).fill("#f9fafb");
      doc.fontSize(10).fillColor("#111827")
        .text(item.description, 60, y)
        .text(String(item.quantity), 300, y)
        .text(`Rs.${item.rate}`, 370, y)
        .text(`Rs.${item.amount}`, 460, y);
      y += 25;
    });

    // Totals
    y += 10;
    doc.moveTo(350, y).lineTo(550, y).strokeColor("#e5e7eb").stroke();
    y += 10;
    doc.fontSize(10).fillColor("#6b7280").text("Subtotal:", 370, y);
    doc.fillColor("#111827").text(`Rs.${invoice.subtotal}`, 460, y);
    y += 18;
    doc.fillColor("#6b7280").text("GST (18%):", 370, y);
    doc.fillColor("#111827").text(`Rs.${invoice.tax}`, 460, y);
    y += 18;
    doc.rect(350, y, 200, 25).fill("#6366f1");
    doc.fontSize(12).fillColor("#ffffff")
      .text("TOTAL:", 370, y + 6)
      .text(`Rs.${invoice.total}`, 460, y + 6);

    // Notes
    y += 50;
    doc.fontSize(10).fillColor("#6b7280").text("Notes:", 50, y);
    doc.fillColor("#111827").text(invoice.notes, 50, y + 15);
    doc.fillColor("#6366f1").text(invoice.thank_you_message, 50, y + 35);

    // Footer
    doc.fontSize(8).fillColor("#9ca3af")
      .text("Generated by FlowConnect • flowconnect.app", 50, 750, { align: "center" });

    doc.end();
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  return { invoice, filePath };
}

// ── Core: Send WhatsApp ───────────────────────────────────────────
async function sendWhatsApp({ phone, invoice_number, amount, customer_name, company_name }) {
  let clean = phone.trim().replace(/\s/g, "");
  if (!clean.startsWith("+")) clean = "+91" + clean;

  const message =
    `🧾 *Invoice from ${company_name || "FlowConnect"}*\n\n` +
    `Hello ${customer_name}!\n\n` +
    `Your invoice is ready:\n` +
    `- Invoice #: *${invoice_number}*\n` +
    `- Amount: *Rs.${amount}*\n` +
    `- Date: ${new Date().toLocaleDateString("en-IN")}\n\n` +
    `Thank you for your payment! ✅\n\n` +
    `_Powered by FlowConnect_`;

  const resp = await axios.post(
    `https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,
    new URLSearchParams({
      From: process.env.TWILIO_WHATSAPP_FROM,
      To: `whatsapp:${clean}`,
      Body: message,
    }),
    { auth: { username: process.env.TWILIO_ACCOUNT_SID, password: process.env.TWILIO_AUTH_TOKEN } }
  );

  return { message_sid: resp.data.sid, sent_to: `whatsapp:${clean}` };
}

// ── Core: Full flow ───────────────────────────────────────────────
async function processPaymentInvoice(params) {
  const { invoice, filePath } = await generateInvoice(params);
  console.log(`📄 PDF saved: ${filePath}`);

  let whatsapp = null;
  try {
    whatsapp = await sendWhatsApp({
      phone:          params.customer_phone,
      invoice_number: invoice.invoice_number,
      amount:         invoice.total,
      customer_name:  params.customer_name,
      company_name:   params.company_name || "FlowConnect",
    });
    console.log(`📱 WhatsApp sent: ${whatsapp.sent_to}`);
  } catch (e) {
    console.error("⚠️  WhatsApp failed:", e.message);
    whatsapp = { error: e.message };
  }

  return { invoice, filePath, whatsapp };
}

// ── Razorpay signature verification ──────────────────────────────
function verifyRazorpaySignature(rawBody, signature) {
  const secret = process.env.RAZORPAY_WEBHOOK_SECRET;
  if (!secret) {
    console.warn("⚠️  RAZORPAY_WEBHOOK_SECRET not set — skipping signature check");
    return true;
  }
  const expected = crypto.createHmac("sha256", secret).update(rawBody).digest("hex");
  return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature || ""));
}

// ── Razorpay Webhook ──────────────────────────────────────────────
app.post("/webhook/razorpay", async (req, res) => {
  const signature = req.headers["x-razorpay-signature"];

  if (!verifyRazorpaySignature(req.body, signature)) {
    console.error("❌ Invalid Razorpay signature");
    return res.status(400).json({ error: "Invalid signature" });
  }

  let event;
  try {
    event = JSON.parse(req.body.toString());
  } catch {
    return res.status(400).json({ error: "Invalid JSON body" });
  }

  console.log(`📩 Received event: ${event.event}`);
  res.json({ status: "received", event: event.event });

  if (event.event !== "payment.captured") return;

  const payment = event.payload?.payment?.entity;
  if (!payment) return;

  console.log(`💳 Payment captured: ${payment.id} | Rs.${payment.amount / 100}`);

  // ── Idempotency check ───────────────────────────────────────────
  const existingRecord = idempotencyStore.get(payment.id);
  if (existingRecord) {
    console.log(`⚠️  Payment ${payment.id} already processed on ${existingRecord.timestamp}`);
    console.log(`   Invoice: ${existingRecord.invoice_number} (skipping re-processing)`);
    return;
  }

  const deterministicInvoiceNumber = generateDeterministicInvoiceNumber(payment.id);

  try {
    await processPaymentInvoice({
      payment_id:     payment.id,
      amount:         payment.amount / 100,
      customer_name:  payment.notes?.name || payment.notes?.customer_name || "Customer",
      customer_email: payment.email || payment.notes?.email || "noreply@flowconnect.app",
      customer_phone: payment.contact || payment.notes?.phone || "",
      product_name:   payment.description || payment.notes?.product || "Digital Service",
      company_name:   process.env.COMPANY_NAME || "FlowConnect",
      invoice_number_override: deterministicInvoiceNumber,
    });
    
    // ── Mark as processed after success ────────────────────────────
    idempotencyStore.set(payment.id, deterministicInvoiceNumber);
    console.log("✅ Invoice flow completed and marked as processed!");
  } catch (err) {
    console.error("❌ Invoice flow failed:", err.message);
    // Don't mark as processed if an error occurred
    // This allows retries for transient failures
  }
});

// ── Test endpoint ─────────────────────────────────────────────────
app.post("/test/payment", async (req, res) => {
  const { payment_id, amount, customer_name, customer_email, customer_phone, product_name } = req.body;

  if (!payment_id || !amount || !customer_name) {
    return res.status(400).json({ error: "Required: payment_id, amount, customer_name" });
  }

  console.log("🧪 Test payment trigger:", customer_name);

  const deterministicInvoiceNumber = generateDeterministicInvoiceNumber(payment_id);

  try {
    const result = await processPaymentInvoice({
      payment_id,
      amount:         Number(amount),
      customer_name,
      customer_email:  customer_email  || "test@example.com",
      customer_phone:  customer_phone  || "9999999999",
      product_name:    product_name    || "Test Product",
      company_name:    process.env.COMPANY_NAME || "FlowConnect",
      invoice_number_override: deterministicInvoiceNumber,
    });

    res.json({
      success: true,
      invoice_number: result.invoice.invoice_number,
      pdf_path:       result.filePath,
      total:          result.invoice.total,
      whatsapp:       result.whatsapp,
    });
  } catch (err) {
    console.error("❌ Error:", err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

// ── Start ─────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`\n🚀 FlowConnect Webhook Server`);
  console.log(`   Listening on:  http://localhost:${PORT}`);
  console.log(`   Webhook URL:   http://localhost:${PORT}/webhook/razorpay`);
  console.log(`   Test URL:      http://localhost:${PORT}/test/payment`);
  console.log(`   Set this in Razorpay Dashboard → Webhooks:`);
  console.log(`   https://your-domain.com/webhook/razorpay\n`);
});